### ISSUE TITLE
App getting force closed 

### ISSUE THREAD

**Issue by mssaravanan** [iammert/AndroidArchitecture#2]
05-31 15:38:50.877 24942-25015/iammert.com.androidarchitecture E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                                 Process: iammert.com.androidarchitecture, PID: 24942
                                                                                 java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                     at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List iammert.com.androidarchitecture.data.remote.model.MoviesResponse.getResults()' on a null object reference
                                                                                     at iammert.com.androidarchitecture.data.MovieRepository$1.saveCallResult(MovieRepository.java:36)
                                                                                     at iammert.com.androidarchitecture.data.MovieRepository$1.saveCallResult(MovieRepository.java:32)
                                                                                     at iammert.com.androidarchitecture.data.NetworkBoundResource$2.doInBackground(NetworkBoundResource.java:71)
                                                                                     at iammert.com.androidarchitecture.data.NetworkBoundResource$2.doInBackground(NetworkBoundResource.java:67)
                                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by iammert** [comment]
You need to get an API key from https://www.themoviedb.org/settings/api and paste it ApiConstant class. @saran2somu
